### ISSUE TITLE
DoSPA but fail

### ISSUE THREAD

**Issue by nkuwenjian** [ros-perception/slam_karto#18] opened 2017-05-18 03:03 UTC
[ INFO] [1495075422.804255281, 1494847537.362521814]: laser laser's pose wrt base: 0.150 0.000 0.000
Registering sensor: [laser]
[ INFO] [1495075900.451681132, 1494848015.006153533]: Calling doSPA for loop closure
[slam_karto-2] process has died [pid 15130, exit code -11, cmd /home/wenjian/catkin_ws/devel/lib/slam_karto/slam_karto scan:=scan __name:=slam_karto __log:=/home/wenjian/.ros/log/75dfcdca-3b66-11e7-9eb8-6c71d964baf6/slam_karto-2.log].
log file: /home/wenjian/.ros/log/75dfcdca-3b66-11e7-9eb8-6c71d964baf6/slam_karto-2*.log

**Comment by jacobperron** [comment] 2017-05-29 21:41
I've come across the same issue, but haven't been able to narrow down what is causing it. I've noticed it happens a lot with long trajectories (>200m).

**Comment by humanderek** [comment] 2017-06-08 09:35
I have encountered the same problem. Whenever calling doSPA for loop closure, there is a chance that slam karto get crashed.

**Comment by lucbettaieb** [comment] 2017-12-14 01:31
Hi all,

If any of you encounter this again, would you please get a bag of the information it is processing as well as dump whatever logs you find here?  This will help with debugging whatever is going on.

Thanks!

**Comment by nkuwenjian** [comment] 2018-03-18 14:02
I have fixed this bug. The problem will be solved by source installing open_karto and spa library together. If you install open_karto by source installation and install spa by binary installation, you would encounter the above problem. If any of you want to use open_karto and slam_karto by source installation, you can refer to my slam_karto version (https://github.com/WENJIAN0629/slam_karto).

**Comment by lucbettaieb** [comment] 2018-03-19 18:34
Hi @WENJIAN0629 

If you have fixed this bug, would you please make a pull request so we can see what the fix is?  Usually installing things via the source should work fine with things installed via the debians.  Furthermore, it looks as if you copied the repo instead of forking it for your version of `slam_karto`, so I can't tell what the issue was / what your fix is.

**Comment by lucbettaieb** [comment] 2018-03-29 21:36
@WENJIAN0629 I'm going to close this for now.  Please make a pull request if you would like to address this issue.

**Comment by mfe7** [comment] 2018-04-03 22:01
I just tried @WENJIAN0629 's repo/instructions and can confirm it works on my system (ubuntu 16.04/kinetic), whereas this official repo crashes during loop closures.

**Comment by lucbettaieb** [comment] 2018-04-04 18:44
@mfe7 Can you provide more information / open a ticket re the crash and fix?
@WENJIAN0629 If this is indeed an issue, would you please make a PR to fix it?

**Comment by lucbettaieb** [comment] 2018-06-14 21:00
@mfe7 @WENJIAN0629 
Please open a pull request if you'd like to fix this issue.

**Closed as completed** 2018-06-19 18:03 UTC

**Comment by varunagrawal** [comment] 2018-09-26 19:35
@lucbettaieb I think I figured out what the issue is. The CMake file includes `Eigen` whereas @WENJIAN0629 uses `Eigen3`. I made that change in this repo and reran the experiment which was failing on this, and now it seems to work.
I don't think it is an issue in `open_karto` as neither @WENJIAN0629 or I change the source of that repo.

I can open a PR if you'd like.

**Comment by lucbettaieb** [comment] 2018-09-27 14:27
Hey Varun, please open a PR if you’d like so I can see your changes.

**Comment by varunagrawal** [comment] 2018-09-27 20:27
Hey Luc. Please see #22.
